// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mock

import (
	model "github.com/c0llinn/ebook-store/internal/auth/model"
	mock "github.com/stretchr/testify/mock"
)

// EmailClient is an autogenerated mock type for the EmailClient type
type EmailClient struct {
	mock.Mock
}

// SendPasswordResetEmail provides a mock function with given fields: user, newPassword
func (_m *EmailClient) SendPasswordResetEmail(user model.User, newPassword string) error {
	ret := _m.Called(user, newPassword)

	var r0 error
	if rf, ok := ret.Get(0).(func(model.User, string) error); ok {
		r0 = rf(user, newPassword)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
