// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mock

import (
	model "github.com/c0llinn/ebook-store/internal/auth/model"
	mock "github.com/stretchr/testify/mock"
)

// JWTWrapper is an autogenerated mock type for the JWTWrapper type
type JWTWrapper struct {
	mock.Mock
}

// ExtractUserFromToken provides a mock function with given fields: tokenString
func (_m *JWTWrapper) ExtractUserFromToken(tokenString string) (model.User, error) {
	ret := _m.Called(tokenString)

	var r0 model.User
	if rf, ok := ret.Get(0).(func(string) model.User); ok {
		r0 = rf(tokenString)
	} else {
		r0 = ret.Get(0).(model.User)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(tokenString)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GenerateTokenForUser provides a mock function with given fields: user
func (_m *JWTWrapper) GenerateTokenForUser(user model.User) (string, error) {
	ret := _m.Called(user)

	var r0 string
	if rf, ok := ret.Get(0).(func(model.User) string); ok {
		r0 = rf(user)
	} else {
		r0 = ret.Get(0).(string)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(model.User) error); ok {
		r1 = rf(user)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
