// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mock

import mock "github.com/stretchr/testify/mock"

// FilenameGenerator is an autogenerated mock type for the FilenameGenerator type
type FilenameGenerator struct {
	mock.Mock
}

// NewUniqueName provides a mock function with given fields: filename
func (_m *FilenameGenerator) NewUniqueName(filename string) string {
	ret := _m.Called(filename)

	var r0 string
	if rf, ok := ret.Get(0).(func(string) string); ok {
		r0 = rf(filename)
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}
