// Code generated by mockery v2.12.1. DO NOT EDIT.

package mocks

import (
	auth "github.com/c0llinn/ebook-store/internal/auth"
	mock "github.com/stretchr/testify/mock"

	testing "testing"
)

// TokenHandler is an autogenerated mock type for the TokenHandler type
type TokenHandler struct {
	mock.Mock
}

// ExtractUserFromToken provides a mock function with given fields: token
func (_m *TokenHandler) ExtractUserFromToken(token string) (auth.User, error) {
	ret := _m.Called(token)

	var r0 auth.User
	if rf, ok := ret.Get(0).(func(string) auth.User); ok {
		r0 = rf(token)
	} else {
		r0 = ret.Get(0).(auth.User)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(token)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewTokenHandler creates a new instance of TokenHandler. It also registers the testing.TB interface on the mock and a cleanup function to assert the mocks expectations.
func NewTokenHandler(t testing.TB) *TokenHandler {
	mock := &TokenHandler{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
