// Code generated by mockery v2.12.1. DO NOT EDIT.

package mocks

import (
	context "context"

	shop "github.com/c0llinn/ebook-store/internal/shop"
	mock "github.com/stretchr/testify/mock"

	testing "testing"
)

// PaymentClient is an autogenerated mock type for the PaymentClient type
type PaymentClient struct {
	mock.Mock
}

// CreatePaymentIntentForOrder provides a mock function with given fields: ctx, order
func (_m *PaymentClient) CreatePaymentIntentForOrder(ctx context.Context, order *shop.Order) error {
	ret := _m.Called(ctx, order)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *shop.Order) error); ok {
		r0 = rf(ctx, order)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewPaymentClient creates a new instance of PaymentClient. It also registers the testing.TB interface on the mock and a cleanup function to assert the mocks expectations.
func NewPaymentClient(t testing.TB) *PaymentClient {
	mock := &PaymentClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
