// Code generated by mockery v2.12.0. DO NOT EDIT.

package mocks

import (
	context "context"

	model "github.com/c0llinn/ebook-store/internal/shop/model"
	mock "github.com/stretchr/testify/mock"

	testing "testing"
)

// Repository is an autogenerated mock type for the Repository type
type Repository struct {
	mock.Mock
}

// Create provides a mock function with given fields: ctx, order
func (_m *Repository) Create(ctx context.Context, order *model.Order) error {
	ret := _m.Called(ctx, order)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.Order) error); ok {
		r0 = rf(ctx, order)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// FindByID provides a mock function with given fields: ctx, id
func (_m *Repository) FindByID(ctx context.Context, id string) (model.Order, error) {
	ret := _m.Called(ctx, id)

	var r0 model.Order
	if rf, ok := ret.Get(0).(func(context.Context, string) model.Order); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(model.Order)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindByQuery provides a mock function with given fields: ctx, query
func (_m *Repository) FindByQuery(ctx context.Context, query model.OrderQuery) (model.PaginatedOrders, error) {
	ret := _m.Called(ctx, query)

	var r0 model.PaginatedOrders
	if rf, ok := ret.Get(0).(func(context.Context, model.OrderQuery) model.PaginatedOrders); ok {
		r0 = rf(ctx, query)
	} else {
		r0 = ret.Get(0).(model.PaginatedOrders)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, model.OrderQuery) error); ok {
		r1 = rf(ctx, query)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: ctx, order
func (_m *Repository) Update(ctx context.Context, order *model.Order) error {
	ret := _m.Called(ctx, order)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.Order) error); ok {
		r0 = rf(ctx, order)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewRepository creates a new instance of Repository. It also registers the testing.TB interface on the mock and a cleanup function to assert the mocks expectations.
func NewRepository(t testing.TB) *Repository {
	mock := &Repository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
