basePath: /
definitions:
  api.Error:
    properties:
      details:
        type: string
      message:
        type: string
    type: object
  dto.BookResponse:
    properties:
      authorName:
        type: string
      createdAt:
        type: string
      description:
        type: string
      id:
        type: string
      posterImageLink:
        type: string
      price:
        type: integer
      releaseDate:
        type: string
      title:
        type: string
      updatedAt:
        type: string
    type: object
  dto.CreateOrder:
    properties:
      bookId:
        type: string
    required:
      - bookId
    type: object
  dto.CredentialsResponse:
    properties:
      token:
        type: string
    type: object
  dto.LoginRequest:
    properties:
      email:
        type: string
      password:
        type: string
    required:
      - email
      - password
    type: object
  dto.OrderResponse:
    properties:
      bookId:
        type: string
      clientSecret:
        type: string
      createdAt:
        type: string
      id:
        type: string
      paymentIntentId:
        type: string
      status:
        type: string
      total:
        type: integer
      updatedAt:
        type: string
      userId:
        type: string
    type: object
  dto.PaginatedBooksResponse:
    properties:
      currentPage:
        type: integer
      perPage:
        type: integer
      results:
        items:
          $ref: '#/definitions/dto.BookResponse'
        type: array
      totalItems:
        type: integer
      totalPages:
        type: integer
    type: object
  dto.PaginatedOrdersResponse:
    properties:
      currentPage:
        type: integer
      perPage:
        type: integer
      results:
        items:
          $ref: '#/definitions/dto.OrderResponse'
        type: array
      totalItems:
        type: integer
      totalPages:
        type: integer
    type: object
  dto.PasswordResetRequest:
    properties:
      email:
        type: string
    required:
      - email
    type: object
  dto.RegisterRequest:
    properties:
      email:
        type: string
      firstName:
        type: string
      lastName:
        type: string
      password:
        type: string
      passwordConfirmation:
        type: string
    required:
      - email
      - firstName
      - lastName
      - password
      - passwordConfirmation
    type: object
  dto.SearchBooks:
    properties:
      authorName:
        type: string
      description:
        type: string
      page:
        type: integer
      perPage:
        type: integer
      title:
        type: string
    type: object
  dto.SearchOrders:
    properties:
      page:
        type: integer
      perPage:
        type: integer
      status:
        type: string
    type: object
  dto.UpdateBook:
    properties:
      authorName:
        type: string
      description:
        type: string
      title:
        type: string
    type: object
host: localhost:8081
info:
  contact:
    email: raphael_professional@yahoo.com
    name: Raphael Collin
  description: Endpoints available in the E-book store REST API.
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: https://github.com/C0lliNN
  title: E-book Store
  version: "1.0"
paths:
  /books:
    get:
      parameters:
        - description: Filters
          in: body
          name: payload
          required: true
          schema:
            $ref: '#/definitions/dto.SearchBooks'
      produces:
        - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.PaginatedBooksResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/api.Error'
      summary: Fetch Books
      tags:
        - Catalog
    post:
      consumes:
        - multipart/form-data
      parameters:
        - in: formData
          name: authorName
          required: true
          type: string
        - in: formData
          name: description
          required: true
          type: string
        - in: formData
          name: price
          required: true
          type: integer
        - in: formData
          name: releaseDate
          required: true
          type: string
        - in: formData
          name: title
          required: true
          type: string
        - description: Book Poster
          in: formData
          name: poster
          required: true
          type: file
        - description: Book Content in PDF
          in: formData
          name: content
          required: true
          type: file
      produces:
        - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/dto.BookResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/api.Error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/api.Error'
      summary: Create a new Book
      tags:
        - Catalog
  /books/{id}:
    delete:
      parameters:
        - description: Book ID
          in: path
          name: id
          required: true
          type: string
      produces:
        - application/json
      responses:
        "204":
          description: Success
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/api.Error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/api.Error'
      summary: Delete a Book
      tags:
        - Catalog
    get:
      parameters:
        - description: Book ID
          in: path
          name: id
          required: true
          type: string
      produces:
        - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.BookResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/api.Error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/api.Error'
      summary: Fetch Book by ID
      tags:
        - Catalog
    patch:
      consumes:
        - application/json
      parameters:
        - description: Book Payload
          in: body
          name: payload
          required: true
          schema:
            $ref: '#/definitions/dto.UpdateBook'
        - description: Book ID
          in: path
          name: id
          required: true
          type: string
      produces:
        - application/json
      responses:
        "204":
          description: Success
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/api.Error'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/api.Error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/api.Error'
      summary: Update the provided Book
      tags:
        - Catalog
  /login:
    post:
      consumes:
        - application/json
      parameters:
        - description: Register Payload
          in: body
          name: payload
          required: true
          schema:
            $ref: '#/definitions/dto.LoginRequest'
      produces:
        - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/dto.CredentialsResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/api.Error'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/api.Error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/api.Error'
      summary: Login using email and password
      tags:
        - Auth
  /orders:
    get:
      parameters:
        - description: Filters
          in: body
          name: payload
          required: true
          schema:
            $ref: '#/definitions/dto.SearchOrders'
      produces:
        - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.PaginatedOrdersResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/api.Error'
      summary: Fetch Orders
      tags:
        - Shop
    post:
      consumes:
        - application/json
      parameters:
        - description: Order Payload
          in: body
          name: payload
          required: true
          schema:
            $ref: '#/definitions/dto.CreateOrder'
      produces:
        - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/dto.OrderResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/api.Error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/api.Error'
      summary: Create a new Order
      tags:
        - Shop
  /orders/{id}:
    get:
      parameters:
        - description: orderId ID
          in: path
          name: id
          required: true
          type: string
      produces:
        - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.OrderResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/api.Error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/api.Error'
      summary: Fetch Order by ID
      tags:
        - Shop
  /orders/{id}/download:
    get:
      parameters:
        - description: Order Payload
          in: body
          name: payload
          required: true
          schema:
            $ref: '#/definitions/dto.CreateOrder'
      produces:
        - application/pdf
      responses:
        "200":
          description: Success
        "402":
          description: Payment Required
          schema:
            $ref: '#/definitions/api.Error'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/api.Error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/api.Error'
      summary: Download the book for the given Order
      tags:
        - Shop
  /password-reset:
    post:
      consumes:
        - application/json
      parameters:
        - description: Register Payload
          in: body
          name: payload
          required: true
          schema:
            $ref: '#/definitions/dto.PasswordResetRequest'
      produces:
        - application/json
      responses:
        "204":
          description: success
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/api.Error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/api.Error'
      summary: Reset the password for the given email
      tags:
        - Auth
  /register:
    post:
      consumes:
        - application/json
      parameters:
        - description: Register Payload
          in: body
          name: payload
          required: true
          schema:
            $ref: '#/definitions/dto.RegisterRequest'
      produces:
        - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/dto.CredentialsResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/api.Error'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/api.Error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/api.Error'
      summary: Register a new user
      tags:
        - Auth
  /stripe/webhook:
    post:
      consumes:
        - application/json
      produces:
        - application/json
      responses:
        "200":
          description: Success
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/api.Error'
      summary: Handle stripe webhooks
      tags:
        - Shop
swagger: "2.0"
