// Code generated by mockery v2.30.1. DO NOT EDIT.

package mocks

import (
	context "context"

	catalog "github.com/ebookstore/internal/core/catalog"

	mock "github.com/stretchr/testify/mock"
)

// CatalogService is an autogenerated mock type for the CatalogService type
type CatalogService struct {
	mock.Mock
}

// FindBookByID provides a mock function with given fields: ctx, bookId
func (_m *CatalogService) FindBookByID(ctx context.Context, bookId string) (catalog.BookResponse, error) {
	ret := _m.Called(ctx, bookId)

	var r0 catalog.BookResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (catalog.BookResponse, error)); ok {
		return rf(ctx, bookId)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) catalog.BookResponse); ok {
		r0 = rf(ctx, bookId)
	} else {
		r0 = ret.Get(0).(catalog.BookResponse)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, bookId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetBookContentURL provides a mock function with given fields: ctx, bookId
func (_m *CatalogService) GetBookContentURL(ctx context.Context, bookId string) (string, error) {
	ret := _m.Called(ctx, bookId)

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (string, error)); ok {
		return rf(ctx, bookId)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) string); ok {
		r0 = rf(ctx, bookId)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, bookId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewCatalogService creates a new instance of CatalogService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCatalogService(t interface {
	mock.TestingT
	Cleanup(func())
}) *CatalogService {
	mock := &CatalogService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
