// Code generated by mockery v2.40.1. DO NOT EDIT.

package server

import (
	auth "github.com/ebookstore/internal/core/auth"
	mock "github.com/stretchr/testify/mock"
)

// MockTokenHandler is an autogenerated mock type for the TokenHandler type
type MockTokenHandler struct {
	mock.Mock
}

// ExtractUserFromToken provides a mock function with given fields: token
func (_m *MockTokenHandler) ExtractUserFromToken(token string) (auth.User, error) {
	ret := _m.Called(token)

	if len(ret) == 0 {
		panic("no return value specified for ExtractUserFromToken")
	}

	var r0 auth.User
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (auth.User, error)); ok {
		return rf(token)
	}
	if rf, ok := ret.Get(0).(func(string) auth.User); ok {
		r0 = rf(token)
	} else {
		r0 = ret.Get(0).(auth.User)
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(token)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewMockTokenHandler creates a new instance of MockTokenHandler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTokenHandler(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTokenHandler {
	mock := &MockTokenHandler{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
