// Code generated by mockery v2.30.1. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// FilenameGenerator is an autogenerated mock type for the FilenameGenerator type
type FilenameGenerator struct {
	mock.Mock
}

// NewUniqueName provides a mock function with given fields: filename
func (_m *FilenameGenerator) NewUniqueName(filename string) string {
	ret := _m.Called(filename)

	var r0 string
	if rf, ok := ret.Get(0).(func(string) string); ok {
		r0 = rf(filename)
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// NewFilenameGenerator creates a new instance of FilenameGenerator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewFilenameGenerator(t interface {
	mock.TestingT
	Cleanup(func())
}) *FilenameGenerator {
	mock := &FilenameGenerator{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
