// Code generated by mockery v2.12.1. DO NOT EDIT.

package mocks

import (
	context "context"
	io "io"

	mock "github.com/stretchr/testify/mock"

	testing "testing"
)

// StorageClient is an autogenerated mock type for the StorageClient type
type StorageClient struct {
	mock.Mock
}

// GeneratePreSignedUrl provides a mock function with given fields: ctx, key
func (_m *StorageClient) GeneratePreSignedUrl(ctx context.Context, key string) (string, error) {
	ret := _m.Called(ctx, key)

	var r0 string
	if rf, ok := ret.Get(0).(func(context.Context, string) string); ok {
		r0 = rf(ctx, key)
	} else {
		r0 = ret.Get(0).(string)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, key)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RetrieveFile provides a mock function with given fields: ctx, key
func (_m *StorageClient) RetrieveFile(ctx context.Context, key string) (io.ReadCloser, error) {
	ret := _m.Called(ctx, key)

	var r0 io.ReadCloser
	if rf, ok := ret.Get(0).(func(context.Context, string) io.ReadCloser); ok {
		r0 = rf(ctx, key)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(io.ReadCloser)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, key)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SaveFile provides a mock function with given fields: ctx, key, contentType, content
func (_m *StorageClient) SaveFile(ctx context.Context, key string, contentType string, content io.ReadSeeker) error {
	ret := _m.Called(ctx, key, contentType, content)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, io.ReadSeeker) error); ok {
		r0 = rf(ctx, key, contentType, content)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewStorageClient creates a new instance of StorageClient. It also registers the testing.TB interface on the mock and a cleanup function to assert the mocks expectations.
func NewStorageClient(t testing.TB) *StorageClient {
	mock := &StorageClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
