// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package app

import (
	"github.com/c0llinn/ebook-store/internal"
)

// Injectors from wire.go:

func SetupApplication() internal.Foo {
	bar := internal.NewBar()
	foo := internal.NewFoo(bar)
	return foo
}
