// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package main

import (
	"github.com/c0llinn/ebook-store/internal/api"
	http2 "github.com/c0llinn/ebook-store/internal/auth/delivery/http"
	"github.com/c0llinn/ebook-store/internal/auth/email"
	"github.com/c0llinn/ebook-store/internal/auth/helper"
	"github.com/c0llinn/ebook-store/internal/auth/middleware"
	"github.com/c0llinn/ebook-store/internal/auth/persistence"
	"github.com/c0llinn/ebook-store/internal/auth/usecase"
	http3 "github.com/c0llinn/ebook-store/internal/catalog/delivery/http"
	helper2 "github.com/c0llinn/ebook-store/internal/catalog/helper"
	repository2 "github.com/c0llinn/ebook-store/internal/catalog/repository"
	"github.com/c0llinn/ebook-store/internal/catalog/storage"
	usecase2 "github.com/c0llinn/ebook-store/internal/catalog/usecase"
	config2 "github.com/c0llinn/ebook-store/internal/config"
	"github.com/c0llinn/ebook-store/internal/shop/client"
	http4 "github.com/c0llinn/ebook-store/internal/shop/delivery/http"
	helper3 "github.com/c0llinn/ebook-store/internal/shop/helper"
	repository3 "github.com/c0llinn/ebook-store/internal/shop/repository"
	usecase3 "github.com/c0llinn/ebook-store/internal/shop/usecase"
	"net/http"
)

// Injectors from wire.go:

func CreateWebServer() *http.Server {
	engine := api.NewRouter()
	gormDB := config2.NewConnection()
	userRepository := persistence.NewUserRepository(gormDB)
	hmacSecret := helper.NewHMACSecret()
	jwtWrapper := helper.NewJWTWrapper(hmacSecret)
	ses := config2.NewSNSService()
	emailClient := email.NewEmailClient(ses)
	passwordGenerator := helper.NewPasswordGenerator()
	bcryptWrapper := helper.NewBcryptWrapper()
	authUseCase := usecase.NewAuthUseCase(userRepository, jwtWrapper, emailClient, passwordGenerator, bcryptWrapper)
	uuidGenerator := helper.NewUUIDGenerator()
	authHandler := http2.NewAuthHandler(authUseCase, uuidGenerator)
	bookRepository := repository2.NewBookRepository(gormDB)
	s3 := config2.NewS3Service()
	bucket := config2.NewBucket()
	s3Client := storage.NewS3Client(s3, bucket)
	filenameGenerator := helper2.NewFilenameGenerator()
	catalogUseCase := usecase2.NewCatalogUseCase(bookRepository, s3Client, filenameGenerator)
	idGenerator := helper2.NewIDGenerator()
	catalogHandler := http3.NewCatalogHandler(catalogUseCase, idGenerator)
	orderRepository := repository3.NewOrderRepository(gormDB)
	stripeClient := client.NewStripeClient()
	shopUseCase := usecase3.NewShopUseCase(orderRepository, stripeClient, catalogUseCase)
	helperIDGenerator := helper3.NewIDGenerator()
	shopHandler := http4.NewShopHandler(shopUseCase, helperIDGenerator)
	authenticationMiddleware := middleware.NewAuthenticationMiddleware(jwtWrapper)
	adminMiddleware := middleware.NewAdminMiddleware()
	server := api.NewHttpServer(engine, authHandler, catalogHandler, shopHandler, authenticationMiddleware, adminMiddleware)
	return server
}
