// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package main

import (
	"github.com/c0llinn/ebook-store/config"
	"github.com/c0llinn/ebook-store/internal"
)

// Injectors from wire.go:

func SetupApplication() internal.Repository {
	db := config.NewConnection()
	repository := internal.NewRepository(db)
	return repository
}
