// Code generated by mockery v2.12.0. DO NOT EDIT.

package mocks

import (
	context "context"

	auth "github.com/c0llinn/ebook-store/internal/auth"

	mock "github.com/stretchr/testify/mock"

	testing "testing"
)

// EmailClient is an autogenerated mock type for the EmailClient type
type EmailClient struct {
	mock.Mock
}

// SendPasswordResetEmail provides a mock function with given fields: ctx, user, newPassword
func (_m *EmailClient) SendPasswordResetEmail(ctx context.Context, user auth.User, newPassword string) error {
	ret := _m.Called(ctx, user, newPassword)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, auth.User, string) error); ok {
		r0 = rf(ctx, user, newPassword)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewEmailClient creates a new instance of EmailClient. It also registers the testing.TB interface on the mock and a cleanup function to assert the mocks expectations.
func NewEmailClient(t testing.TB) *EmailClient {
	mock := &EmailClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
