// Code generated by mockery v2.12.0. DO NOT EDIT.

package mocks

import (
	testing "testing"

	mock "github.com/stretchr/testify/mock"
)

// PasswordGenerator is an autogenerated mock type for the PasswordGenerator type
type PasswordGenerator struct {
	mock.Mock
}

// NewPassword provides a mock function with given fields:
func (_m *PasswordGenerator) NewPassword() string {
	ret := _m.Called()

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// NewPasswordGenerator creates a new instance of PasswordGenerator. It also registers the testing.TB interface on the mock and a cleanup function to assert the mocks expectations.
func NewPasswordGenerator(t testing.TB) *PasswordGenerator {
	mock := &PasswordGenerator{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
