// Code generated by mockery v2.9.4. DO NOT EDIT.

package mock

import (
	model "github.com/c0llinn/ebook-store/internal/shop/model"
	mock "github.com/stretchr/testify/mock"
)

// PaymentClient is an autogenerated mock type for the PaymentClient type
type PaymentClient struct {
	mock.Mock
}

// CreatePaymentIntentForOrder provides a mock function with given fields: order
func (_m *PaymentClient) CreatePaymentIntentForOrder(order *model.Order) error {
	ret := _m.Called(order)

	var r0 error
	if rf, ok := ret.Get(0).(func(*model.Order) error); ok {
		r0 = rf(order)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
