// Code generated by mockery v2.40.1. DO NOT EDIT.

package shop

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockPaymentClient is an autogenerated mock type for the PaymentClient type
type MockPaymentClient struct {
	mock.Mock
}

// CreatePaymentIntentForOrder provides a mock function with given fields: ctx, order
func (_m *MockPaymentClient) CreatePaymentIntentForOrder(ctx context.Context, order *Order) error {
	ret := _m.Called(ctx, order)

	if len(ret) == 0 {
		panic("no return value specified for CreatePaymentIntentForOrder")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *Order) error); ok {
		r0 = rf(ctx, order)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewMockPaymentClient creates a new instance of MockPaymentClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPaymentClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPaymentClient {
	mock := &MockPaymentClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
