// Code generated by mockery v2.40.1. DO NOT EDIT.

package auth

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockEmailClient is an autogenerated mock type for the EmailClient type
type MockEmailClient struct {
	mock.Mock
}

// SendPasswordResetEmail provides a mock function with given fields: ctx, user, newPassword
func (_m *MockEmailClient) SendPasswordResetEmail(ctx context.Context, user User, newPassword string) error {
	ret := _m.Called(ctx, user, newPassword)

	if len(ret) == 0 {
		panic("no return value specified for SendPasswordResetEmail")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, User, string) error); ok {
		r0 = rf(ctx, user, newPassword)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewMockEmailClient creates a new instance of MockEmailClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockEmailClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockEmailClient {
	mock := &MockEmailClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
