// Code generated by mockery v2.40.1. DO NOT EDIT.

package catalog

import (
	context "context"

	query "github.com/ebookstore/internal/core/query"
	mock "github.com/stretchr/testify/mock"
)

// MockRepository is an autogenerated mock type for the Repository type
type MockRepository struct {
	mock.Mock
}

// Create provides a mock function with given fields: ctx, book
func (_m *MockRepository) Create(ctx context.Context, book *Book) error {
	ret := _m.Called(ctx, book)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *Book) error); ok {
		r0 = rf(ctx, book)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Delete provides a mock function with given fields: ctx, id
func (_m *MockRepository) Delete(ctx context.Context, id string) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// FindByID provides a mock function with given fields: ctx, id
func (_m *MockRepository) FindByID(ctx context.Context, id string) (Book, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 Book
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (Book, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) Book); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(Book)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindByQuery provides a mock function with given fields: ctx, _a1, page
func (_m *MockRepository) FindByQuery(ctx context.Context, _a1 query.Query, page query.Page) (PaginatedBooks, error) {
	ret := _m.Called(ctx, _a1, page)

	if len(ret) == 0 {
		panic("no return value specified for FindByQuery")
	}

	var r0 PaginatedBooks
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, query.Query, query.Page) (PaginatedBooks, error)); ok {
		return rf(ctx, _a1, page)
	}
	if rf, ok := ret.Get(0).(func(context.Context, query.Query, query.Page) PaginatedBooks); ok {
		r0 = rf(ctx, _a1, page)
	} else {
		r0 = ret.Get(0).(PaginatedBooks)
	}

	if rf, ok := ret.Get(1).(func(context.Context, query.Query, query.Page) error); ok {
		r1 = rf(ctx, _a1, page)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: ctx, book
func (_m *MockRepository) Update(ctx context.Context, book *Book) error {
	ret := _m.Called(ctx, book)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *Book) error); ok {
		r0 = rf(ctx, book)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewMockRepository creates a new instance of MockRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRepository {
	mock := &MockRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
